set-option -g default-shell /usr/bin/fish

unbind C-b
# unbind 
# unbind C-b
# set -g prefix C-a
set -g prefix m-'\'

bind m-'\' send-prefix

bind a display-panes
bind v split-window -h
bind x split-window -v


# Load default .tmux.conf
# source-file ~/.tmux.conf

# setup octoly session
# new-session -s viewer -n viewer -d
# new-session -s sqlite_browser -n viewer
# send-keys 'ls' Enter

# split-window -v -p 15 -c ~/code/octoly
# send-keys 'drails c' Enter
# split-window -h -p 50 -c ~/code/octoly
# 
# # Select vim pane 
# select-pane -t 1
# 
# # create second window
# new-window -n server -c ~/code/octoly
# send-keys 'fd' Enter
# 
# split-window -h -p 50 -c ~/code/octoly
# send-keys 'drails s' Enter
# 
# select-pane -t 1
# split-window -v -p 50 -c ~/code/octoly
# send-keys 'be guard' Enter
# 
# # Optional step, reselect window 1 (the one with vim)
# select-window -t editor
