#!/usr/bin/bash
# this script handles all stowing related to the $DOTS_ROOT directory

if [[ $EUID -eq 0 ]]; then
  echo "This script must NOT be run as root" 1>&2
  exit 1
fi

DOTS_ROOT=$DOTS

MODE='reload'
MACHINE=`hostnamectl hostname`
LOG_LVL=0


while getopts "ridm:p" FLAG; do
    case "$FLAG" in
        r) MODE='reload';;
        i) MODE='init';;
        d) MODE='delete';;
        m) MACHINE=$OPTARG;;
        p) DOTS_ROOT=`pwd`;;
    esac
done

print() {
    echo "$1: $2"
}

section() {
    echo -e "\n$1: $2"
}

init() {
    print "init" "HOME"
    $DOTS_ROOT/init_dirs
    stow --verbose=$LOG_LVL -S -d . -t ~ home
}

delete() {
    print " del" "HOME"
    stow --verbose=$LOG_LVL -D -d . -t ~ home
}

reload() {
    delete
    init
}

operate_on_pwd() {
    case $1 in
        "reload") reload ;;
        "init") init ;;
        "delete") delete ;;
    esac
}

operate() {
    cd $DOTS_ROOT/common
    section "common"
    operate_on_pwd $1

    if [ -d "$DOTS_ROOT/machines/$MACHINE" ]; then
        cd $DOTS_ROOT/machines/$MACHINE
        section $MACHINE
        operate_on_pwd $1
    fi
}

operate $MODE
