#!/usr/bin/bash

mkdir -p ~/.local/share/applications
mkdir -p ~/.local/bin

mkdir -p ~/.local/arch_pkgs
mkdir -p ~/.local/arch_pkgs/dumb-fonts
mkdir -p ~/.local/arch_pkgs/flat-remix-custom-gtk-theme
mkdir -p ~/.local/arch_pkgs/wine-meta

mkdir -p ~/.config
mkdir -p ~/.config/ncmpcpp
mkdir -p ~/.config/transmission
mkdir -p ~/.config/mpv

mkdir -p ~/.mozilla/firefox/profile_potato
