#!/usr/bin/bash
# this script handles all stowing related to the $DOTS_ROOT directory

DOTS_ROOT=`pwd`
# DOTS_ROOT=$DOTS
MACHINE=`hostnamectl hostname`

section() {
    echo -e "\n$1: $2"
}

copy_sys_dots() {
    SYS_DOTS_ROOT=$1

    for LOCAL_LINE in `find $SYS_DOTS_ROOT`; do
        LINE=${LOCAL_LINE:${#SYS_DOTS_ROOT}}

        if [ -z $LINE ]; then continue ;fi

        if [ -d $LOCAL_LINE ]; then
            sudo mkdir -p "$LINE"
        fi

        if [ -f $LOCAL_LINE ]; then
            sudo cp "$LOCAL_LINE" "$LINE"
            echo "$LINE"
        fi
    done
}

section "source" "common"
copy_sys_dots "$DOTS_ROOT/common/system"
section "source" "$MACHINE"
copy_sys_dots "$DOTS_ROOT/machines/$MACHINE/system"
