#! /bin/sh

# aliases
alias once="execute -o -c"
alias reload="execute -r -c"

# COMMANDS
# /usr/share/X11/xkb/rules/base.lst
# setxkbmap -layout us,ara -option 'grp:alt_shift_toggle'
# setxkbmap -layout us

# xrandr --output DVI-D-0 --mode 1920x1080 --output HDMI-0 --mode 1366x768 --right-of DVI-D-0
xwallpaper --zoom ~/media/pics/wallpapers/12.png
xrdb ~/.config/x11/xresources
xmodmap ~/.config/x11/xmodmap

xsetroot -cursor_name left_ptr
# moue, keyboard, bell
xset m 20/10 10
xset r rate 300 30
xset b on
# screen saver and dpms
xset s blank
xset s on
xset s 300 300
# xset s noexpose
xset dpms 300 0 0

wmname LG3D
# numlockx on
# redshift -x
# redshift -O 6000K -b 0.9

# DAEMONIZED PROCESSES (executed only if not running)
once 'xsettingsd'
once 'mpd'
once 'polkit-dumb-agent'
once 'barriers -f -c .config/barrier/config.conf --disable-crypto'
once 'nm-applet'
once 'unclutter --timeout 3 --jitter 10 --ignore-scrolling'
once 'udiskie -asm nested'
once 'picom --experimental-backends'
once 'sxhkd'
once 'xss-lock lock'
once 'transmission-gtk -m'
once 'thunar --daemon'
# once 'spacefm -d'
# once 'urserver start'
# once 'pcmanfm -d' -e "SHELL=$TERM_SHELL"
# once 'mpDris2'
# once 'volumeicon'
# once 'redshift -r -l 39:35'
# once "redshift -r -l `lonlat`"
# replay-sorcery &
# lf -server &


# RE-EXECUTED PROCESSES (killed and executed)
reload 'trayer --align right --widthtype request --transparent true --tint 0x000000'
reload 'dunst'
reload 'flashfocus'
reload 'shortsig'
# reload 'polybar krastiva -r'

# SIGNALS
killall -USR1 xst
killall -USR1 sxhkd
killall -USR1 picom
# pkill -USR1 redshift
# killall -SIGUSR1 dunst # pause


# pkill replay-sorcery; replay-sorcery &
# pkill syncthing-gtk; syncthing-gtk -m &
# pkill twmnd; twmnd &
# pkill lemon_launcher; pkill lemonbar; ~/.config/lemonbar/lemon_launcher &
# pkill yambar; yambar &

# pkill picom; picom=~/sectors/c/picom/build/src/picom
# pkill picom; picom-epic-animations --experimental-backends &


# TESTING
# cd sectors/go/shortsig
# once 'go run shortsig'
# cd ~
