# vim: syntax=sh
# https://developer.gnome.org/gtk3/unstable/GtkSettings.html
# https://github.com/derat/xsettingsd/wiki/Settings

# Net/ThemeName "Pop-nord-dark"
# Net/ThemeName "Skeuos-Red-Dark"
# Net/IconThemeName "Papirus-Dark"
Gtk/CursorThemeName "vimix-cursors-white"
