#!/usr/bin/env bash

cwd="$(dirname "$0")"
source "$cwd/rofi-common"


declare -a DEVICES

function fetch_device_info() {
  local ADDR=$1
  local RAW_INFO=$(bluetoothctl info "$ADDR")

  # push info to array
  local NAME=$(echo "$RAW_INFO" | awk -F ': ' '/Name/ {print $2}')
  local ICON=$(echo "$RAW_INFO" | awk -F ': ' '/Icon/ {print $2}')
  local CONNECTED=$(echo "$RAW_INFO" | awk -F ': ' '/Connected/ {print $2}')
  local BLOCKED=$(echo "$RAW_INFO" | awk -F ': ' '/Blocked/ {print $2}')
  local TRUSTED=$(echo "$RAW_INFO" | awk -F ': ' '/Trusted/ {print $2}')
  local PAIRED=$(echo "$RAW_INFO" | awk -F ': ' '/Paired/ {print $2}')
  local BONDED=$(echo "$RAW_INFO" | awk -F ': ' '/Bonded/ {print $2}')

  local INFO="$NAME|$ICON|$CONNECTED|$BLOCKED|$TRUSTED|$PAIRED|$BONDED|$ADDR"
  echo $INFO
}

function fetch_devices() {
  IFS=$'\n'
  for ADDR in $(bluetoothctl devices | awk '{print $2}'); do
    local INFO=$(fetch_device_info "$ADDR")
    DEVICES+=("$INFO")
  done
}

function list_devices() {
  for i in "${DEVICES[@]}"; do
    local NAME=$(echo "$i" | awk -F '|' '{print $1}')
    local ICON=$(echo "$i" | awk -F '|' '{print $2}')
    local CONNECTED=$(echo "$i" | awk -F '|' '{print $3}')
    local BLOCKED=$(echo "$i" | awk -F '|' '{print $4}')
    local TRUSTED=$(echo "$i" | awk -F '|' '{print $5}')
    local PAIRED=$(echo "$i" | awk -F '|' '{print $6}')
    local BONDED=$(echo "$i" | awk -F '|' '{print $7}')
    local ADDR=$(echo "$i" | awk -F '|' '{print $8}')

    # 1 = connected
    # 2 = disconnected
    local STATUS=
    if [ "$CONNECTED" = "yes" ]; then
      STATUS="─"
    elif [ "$CONNECTED" = "no" ]; then
      STATUS=" "
    elif [ "$BLOCKED" = "yes" ]; then
      STATUS="×"
    fi

    # echo "$i"
    entry "$STATUS $NAME" icon "$ICON-symbolic" info "$ADDR"
  done
}

if [ -n "$1" ]; then
  ADDR="$ROFI_INFO"

  RAW_INFO=$(bluetoothctl info "$ADDR")
  CONNECTED=$(echo "$RAW_INFO" | awk -F ': ' '/Connected/ {print $2}')
  # BLOCKED=$(echo "$RAW_INFO" | awk -F ': ' '/Blocked/ {print $2}')

  if [ "$CONNECTED" = "yes" ]; then
    bluetoothctl disconnect "$ADDR" 1>&2 2>/dev/null &
  else
    bluetoothctl connect "$ADDR" 1>&2 2>/dev/null &
  fi
else
  fetch_devices
  list_devices
fi
