Section "Device"
  Identifier  "Nvidia Card"
  Driver      "nvidia"
  VendorName  "NVIDIA Corporation"
  BoardName   "GeForce GTX 1050 Ti"
  # Option      "RegistryDwords" "RMUseSwI2c=0x01; RMI2cSpeed=100"
EndSection

Section "Screen"
  Identifier  "Screen0"
  Device      "Device0"
  Monitor     "Monitor0"
  Option      "MetaModes" "nvidia-auto-select +0+0 {ForceFullCompositionPipeline=On}"
  Option      "AllowIndirectGLXProtocol" "off"
  Option      "TripleBuffer" "on"
EndSection
