#!/bin/bash


SHELL=bash ~/.config/bspwm/startup
bspc config external_rules_command ~/.config/bspwm/external-rules.sh

# move to external rules
# bspc rule -a scratchpad sticky=on state=floating hidden=on


bspc monitor -d 1 2 3 4 5 6

# bspc monitor DVI-D-0 -d 1 2 3 4 5
# bspc monitor HDMI-0 -d 6 7 8 9 S

bspc config focused_border_color	    "`xgetres col.sel`"
bspc config normal_border_color		    "`xgetres col.mg`"
bspc config active_border_color		    "`xgetres col.tr`"
bspc config presel_feedback_color	    "`xgetres col.fg`"
bspc config presel_border_color		    "`xgetres col.tr`"

bspc config border_width                    0
bspc config window_gap                      10
bspc config split_ratio                     0.5
bspc config pointer_motion_interval         7

bspc config borderless_monocle              true
bspc config gapless_monocle                 true
bspc config focus_follows_pointer           true
bspc config remove_disabled_monitors	    true
bspc config remove_unplugged_monitors	    true
bspc config honor_size_hints                false

# bspc config removal_adjustment            false
# bspc config pointer_follows_focus         false
# bspc config pointer_follows_monitor       false
# bspc config single_monocle                true
# bspc config center_pseudo_tiled           true
# bspc config border_radius                 8

# bspc config merge_overlapping_monitors    true

# bspc config top_padding                   0
# bspc config bottom_padding                0
# bspc config left_padding                  0
# bspc config right_padding                 0

# bspc config pointer_modifier              mod4
# bspc config pointer_action1               move
# bspc config pointer_action2               resize_corner
# bspc config pointer_action3               resize_side
