#!/bin/sh

# NOTE: this is't needed when using ly-dm
[ -f /etc/xprofile ] && . /etc/xprofile ]
[ -f $HOME/.xprofile ] && . $HOME/.xprofile ]


# source xinitrc.d files
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# rfkill unblock all

lxpolkit &

exec herbstluftwm --locked
# exec sxwm
# exec steamos-session
# exec dwm
# exec firefox
# exec dwm
# exec awesome
