backend = "glx";
vsync = false;
refresh_rate = 60;
# use-damage = true;

xrender-sync-fence = true;
# glx-no-stencil = true;
# glx-no-rebind-pixmap = true;

# use-ewmh-active-win = true;
# unredir-if-possible = true;
# detect-transient = true;
# detect-client-leader = true;

# dim
# inactive-dim = 0.35

# Fade
# fading = true
# fade-in-step = 0.1
# fade-out-step = 0.1
# no-fading-destroyed-argb = true

# animations = true
# animation-stiffness = 500


detect-client-opacity = true;


#Shadow 
shadow = true;
shadow-radius = 15;
shadow-offset-y = -15;
shadow-offset-x = -15;
shadow-opacity = 1;
shadow-exclude = [
    "class_g = 'Polybar'",
    "class_g = 'firefox' && window_type = 'utility'",
]

# #Fading
# fading = true;
# fade-in-step = 0.075;
# fade-out-step = 0.075;
# 
# #Corners
# corner-radius = 10;
# round-borders = 0;
# rounded-corners-exclude = [
#   "class_g = 'Polybar'",
#   "window_type = 'tooltip'",
# ];
# 
# wintypes:
# {
#   dnd = { shadow = false; }
#   popup_menu = { shadow = false; }
#   dropdown_menu = { shadow = false; }
# };
