# vim: syntax=conf

backend = "glx"
vsync = false
refresh_rate = 60
use-damage = false

xrender-sync-fence = true
# glx-no-stencil = true
# glx-no-rebind-pixmap = true

# use-ewmh-active-win = true
# unredir-if-possible = true
# detect-transient = true
# detect-client-leader = true


# dim
# inactive-dim = 0.35

# Fade
fading = true
fade-in-step = 0.1
fade-out-step = 0.1
no-fading-destroyed-argb = true

# Animations
animations = true
# animation-clamping = false
animation-stiffness = 400
# animation-dampening = 25
# animation-window-mass = 1.0
# animation-for-open-window = "zoom"

detect-client-opacity = true

#Shadow 
shadow = true
shadow-radius = 15
shadow-offset-y = -15
shadow-offset-x = -15
shadow-opacity = 1
shadow-exclude = [
    "class_g = 'Polybar'",
    "class_g = 'firefox'",
    "class_g = 'pentablet'",
    "class_g = 'Windscribe2'",
    "class_g = 'trayer'",
    "class_g = 'lxqt-notificationd'",
    "class_g = 'umess'"
    # "class_g = 'firefox' && window_type = 'utility'",
    # "class_g = 'firefoxdeveloperedition' && window_type = 'utility'",
]

opacity-rule = [
    "40:class_g = 'Bspwm' && class_i = 'presel_feedback'",
    "80:class_g = 'lxqt-notificationd'",
]
