title       Default
version     5.18.6-zen1-1-zen
machine-id  93bf0f6cba404b24948f4e92c0abeba0
options     root="LABEL=arch_root" rw systemd.machine_id=93bf0f6cba404b24948f4e92c0abeba0 systemd.machine_id=93bf0f6cba404b24948f4e92c0abeba0 intel_iommu=on iommu=pt kvm.ignore_msrs=1 kvm.report_ignored_msrs=0 video=vesafb:off video=efifb:off rd.driver.pre=vfio-pci nouveau.modeset=0 pcie_acs_override=downstream,multifunction
linux       /93bf0f6cba404b24948f4e92c0abeba0/5.18.6-zen1-1-zen/linux
initrd      /93bf0f6cba404b24948f4e92c0abeba0/5.18.6-zen1-1-zen/initrd
